/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.college.view.admin.add;

import com.college.controller.AutomobileController;
import com.college.controller.manager.ControllerManager;
import com.college.model.Automobile;
import com.college.view.interfaces.Showable;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Vagid Zibliuc
 */
public class AutomobileDataForm extends javax.swing.JFrame {

    private final Showable lastForm;
    private AutomobileController automobileController;
    private Automobile automobile;

    /**
     * Creates new form AutomobileDataForm
     *
     * @param lastForm
     */
    public AutomobileDataForm(Showable lastForm) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lastForm = lastForm;
        automobileController = ControllerManager.getAutomobileController();
        uploadComboBox();
    }

    public AutomobileDataForm(Showable lastForm, Automobile automobile) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lastForm = lastForm;
        this.automobile = automobile;
        automobileController = ControllerManager.getAutomobileController();
        uploadComboBox();
        setValues();
    }

    private void uploadComboBox() {
        List<String> bodyTypes = automobileController.getBodyTypes();
        bodyTypes.forEach(e -> bodyComboBox.addItem(e));
    }

    private void setValues() {
        markTextField.setText(automobile.getMark());
        modelTextField.setText(automobile.getModel());
        bodyComboBox.setSelectedItem(automobile.getBodyType());
        placeTextField.setText(String.valueOf(automobile.getPlaceCount()));
        prodTextField.setText(String.valueOf(automobile.getProdYear()));
        photoTextField.setText(automobile.getImagePath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        markTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        inputPanel1 = new javax.swing.JPanel();
        infoLabel1 = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        inputPanel2 = new javax.swing.JPanel();
        infoLabel2 = new javax.swing.JLabel();
        bodyComboBox = new javax.swing.JComboBox<>();
        inputPanel3 = new javax.swing.JPanel();
        infoLabel3 = new javax.swing.JLabel();
        placeTextField = new javax.swing.JTextField();
        inputPanel4 = new javax.swing.JPanel();
        infoLabel4 = new javax.swing.JLabel();
        prodTextField = new javax.swing.JTextField();
        inputPanel5 = new javax.swing.JPanel();
        infoLabel5 = new javax.swing.JLabel();
        photoButton = new javax.swing.JButton();
        photoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Automobile");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Add Automobile");

        infoLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel.setText("Mark");

        markTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(markTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        saveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        infoLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel1.setText("Model");

        modelTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel1Layout = new javax.swing.GroupLayout(inputPanel1);
        inputPanel1.setLayout(inputPanel1Layout);
        inputPanel1Layout.setHorizontalGroup(
            inputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel1Layout.setVerticalGroup(
            inputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel1)
                .addGap(18, 18, 18)
                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel2.setText("Body Type");

        bodyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel2Layout = new javax.swing.GroupLayout(inputPanel2);
        inputPanel2.setLayout(inputPanel2Layout);
        inputPanel2Layout.setHorizontalGroup(
            inputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel2)
                    .addComponent(bodyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel2Layout.setVerticalGroup(
            inputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel2)
                .addGap(18, 18, 18)
                .addComponent(bodyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel3.setText("Place Count");

        placeTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel3Layout = new javax.swing.GroupLayout(inputPanel3);
        inputPanel3.setLayout(inputPanel3Layout);
        inputPanel3Layout.setHorizontalGroup(
            inputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel3Layout.setVerticalGroup(
            inputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel3)
                .addGap(18, 18, 18)
                .addComponent(placeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel4.setText("Production Year");

        prodTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel4Layout = new javax.swing.GroupLayout(inputPanel4);
        inputPanel4.setLayout(inputPanel4Layout);
        inputPanel4Layout.setHorizontalGroup(
            inputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel4Layout.setVerticalGroup(
            inputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel4)
                .addGap(18, 18, 18)
                .addComponent(prodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel5.setText("Photo link");

        photoButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        photoButton.setText("Choose photo");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        photoTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        photoTextField.setEnabled(false);

        javax.swing.GroupLayout inputPanel5Layout = new javax.swing.GroupLayout(inputPanel5);
        inputPanel5.setLayout(inputPanel5Layout);
        inputPanel5Layout.setHorizontalGroup(
            inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanel5Layout.createSequentialGroup()
                        .addComponent(infoLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inputPanel5Layout.createSequentialGroup()
                        .addComponent(photoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(photoTextField)
                        .addGap(25, 25, 25))))
        );
        inputPanel5Layout.setVerticalGroup(
            inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel5)
                .addGap(18, 18, 18)
                .addGroup(inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(saveButton)
                .addGap(91, 91, 91)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(0, 0, 0)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.lastForm.showWindow();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        boolean isProcessed = false;
        String processedText = "";

        String mark = markTextField.getText();
        String model = modelTextField.getText();
        String bodyType = bodyComboBox.getSelectedItem().toString();
        String placeCount = placeTextField.getText();
        String productionYear = prodTextField.getText();
        String imagePath = photoTextField.getText();

        if (automobile == null) {
            isProcessed = automobileController.saveAutomobile(mark, model, bodyType, placeCount, productionYear, imagePath);
            processedText = "Automobile was added!";
        } else {
            isProcessed = automobileController.updateAutomobile(automobile, mark, model, bodyType, placeCount, productionYear, imagePath);
            processedText = "Automobile was updated!";
        }

        if (isProcessed) {
            JOptionPane.showMessageDialog(this, processedText, "Success", JOptionPane.INFORMATION_MESSAGE);
            lastForm.showWindow();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Some error with this statemnet", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Choose image of automobile");

        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            photoTextField.setText(selectedFile.getAbsolutePath().replace('\\', '/'));
        }
    }//GEN-LAST:event_photoButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.lastForm.showWindow();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bodyComboBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JLabel infoLabel4;
    private javax.swing.JLabel infoLabel5;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel inputPanel1;
    private javax.swing.JPanel inputPanel2;
    private javax.swing.JPanel inputPanel3;
    private javax.swing.JPanel inputPanel4;
    private javax.swing.JPanel inputPanel5;
    private javax.swing.JTextField markTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JButton photoButton;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JTextField placeTextField;
    private javax.swing.JTextField prodTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
