/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.college.view.admin.add;

import com.college.controller.EquipmentController;
import com.college.controller.manager.ControllerManager;
import com.college.model.Automobile;
import com.college.model.Equipment;
import com.college.view.interfaces.Showable;
import javax.swing.JOptionPane;

/**
 *
 * @author Vagid Zibliuc
 */
public class EquipmentDataForm extends javax.swing.JFrame {

    private final EquipmentController equipmentController;
    private final Showable lastForm;
    private final Automobile automobile;
    private Equipment equipment;

    /**
     * Creates new form EquipmentDataForm
     *
     * @param lastForm
     * @param automobile
     */
    public EquipmentDataForm(Showable lastForm, Automobile automobile) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lastForm = lastForm;
        this.equipmentController = ControllerManager.getEquipmentController();
        this.automobile = automobile;
        setTitle();
        uploadComboBox();
    }
    
    public EquipmentDataForm(Showable lastForm, Equipment equipment) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lastForm = lastForm;
        this.equipmentController = ControllerManager.getEquipmentController();
        this.equipment = equipment;
        this.automobile = equipment.getAutomobile();
        setTitle();
        uploadComboBox();
        setValues();
    }

    private void setTitle() {
        markLabel.setText(automobile.getMark());
        modelLabel.setText(automobile.getModel());
    }

    private void uploadComboBox() {

        equipmentController.getEngineTypes().forEach(e -> engTypeComboBox.addItem(e));
        equipmentController.getSuspensionTypes().forEach(e -> suspTypeComboBox.addItem(e));
        equipmentController.getDriveTypes().forEach(e -> driveTypeComboBox.addItem(e));
        equipmentController.getGearboxTypes().forEach(e -> gearTypeComboBox.addItem(e));
        equipmentController.getFuelTypes().forEach(e -> fuelTypeComboBox.addItem(e));
    }
    
    private void setValues() {
        nameTextField.setText(equipment.getName());
        engTextField.setText(equipment.getEngineName());
        engTypeComboBox.setSelectedItem(equipment.getEngineType());
        engVolTextField.setText(String.valueOf(equipment.getEngineVolume()));
        horseTextField.setText(String.valueOf(equipment.getHorsepower()));
        suspTypeComboBox.setSelectedItem(equipment.getSuspensiveType());
        driveTypeComboBox.setSelectedItem(equipment.getDriveType());
        gearTypeComboBox.setSelectedItem(equipment.getGearboxType());
        speedTextField.setText(String.valueOf(equipment.getSpeedCount()));
        fuelTypeComboBox.setSelectedItem(equipment.getFuelType());
        interTextField.setText(equipment.getInterior());
        bodyTextField.setText(equipment.getBodyKit());
        weightTextField.setText(String.valueOf(equipment.getWeigth()));
        priceTextField.setText(String.valueOf(equipment.getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        inputScrollPane = new javax.swing.JScrollPane();
        allInputsPanels = new javax.swing.JPanel();
        autoPanel = new javax.swing.JPanel();
        markLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        inputPanel1 = new javax.swing.JPanel();
        infoLabel1 = new javax.swing.JLabel();
        engTextField = new javax.swing.JTextField();
        inputPanel2 = new javax.swing.JPanel();
        infoLabel2 = new javax.swing.JLabel();
        engTypeComboBox = new javax.swing.JComboBox<>();
        inputPanel3 = new javax.swing.JPanel();
        infoLabel3 = new javax.swing.JLabel();
        engVolTextField = new javax.swing.JTextField();
        inputPanel4 = new javax.swing.JPanel();
        infoLabel4 = new javax.swing.JLabel();
        horseTextField = new javax.swing.JTextField();
        inputPanel5 = new javax.swing.JPanel();
        infoLabel5 = new javax.swing.JLabel();
        suspTypeComboBox = new javax.swing.JComboBox<>();
        inputPanel6 = new javax.swing.JPanel();
        infoLabel6 = new javax.swing.JLabel();
        driveTypeComboBox = new javax.swing.JComboBox<>();
        inputPanel7 = new javax.swing.JPanel();
        infoLabel7 = new javax.swing.JLabel();
        gearTypeComboBox = new javax.swing.JComboBox<>();
        inputPanel8 = new javax.swing.JPanel();
        infoLabel8 = new javax.swing.JLabel();
        speedTextField = new javax.swing.JTextField();
        inputPanel9 = new javax.swing.JPanel();
        infoLabel9 = new javax.swing.JLabel();
        fuelTypeComboBox = new javax.swing.JComboBox<>();
        inputPanel10 = new javax.swing.JPanel();
        infoLabel10 = new javax.swing.JLabel();
        interTextField = new javax.swing.JTextField();
        inputPanel11 = new javax.swing.JPanel();
        infoLabel11 = new javax.swing.JLabel();
        bodyTextField = new javax.swing.JTextField();
        inputPanel12 = new javax.swing.JPanel();
        infoLabel12 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        inputPanel13 = new javax.swing.JPanel();
        infoLabel13 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        inputPanel14 = new javax.swing.JPanel();
        infoLabel14 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equipment");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Add Equipment");

        saveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        inputScrollPane.setBorder(null);

        markLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        markLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        markLabel.setText("Name");

        modelLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        modelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelLabel.setText("Name");

        javax.swing.GroupLayout autoPanelLayout = new javax.swing.GroupLayout(autoPanel);
        autoPanel.setLayout(autoPanelLayout);
        autoPanelLayout.setHorizontalGroup(
            autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(markLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autoPanelLayout.setVerticalGroup(
            autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(markLabel)
                .addGap(18, 18, 18)
                .addComponent(modelLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        infoLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel1.setText("Engine name");

        engTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel1Layout = new javax.swing.GroupLayout(inputPanel1);
        inputPanel1.setLayout(inputPanel1Layout);
        inputPanel1Layout.setHorizontalGroup(
            inputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel1)
                    .addComponent(engTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPanel1Layout.setVerticalGroup(
            inputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel1)
                .addGap(18, 18, 18)
                .addComponent(engTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel2.setText("Engine Type");

        engTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel2Layout = new javax.swing.GroupLayout(inputPanel2);
        inputPanel2.setLayout(inputPanel2Layout);
        inputPanel2Layout.setHorizontalGroup(
            inputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel2)
                    .addComponent(engTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel2Layout.setVerticalGroup(
            inputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel2)
                .addGap(18, 18, 18)
                .addComponent(engTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel3.setText("Engine Volume");

        engVolTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel3Layout = new javax.swing.GroupLayout(inputPanel3);
        inputPanel3.setLayout(inputPanel3Layout);
        inputPanel3Layout.setHorizontalGroup(
            inputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(engVolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel3Layout.setVerticalGroup(
            inputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel3)
                .addGap(18, 18, 18)
                .addComponent(engVolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel4.setText("Horsepower");

        horseTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel4Layout = new javax.swing.GroupLayout(inputPanel4);
        inputPanel4.setLayout(inputPanel4Layout);
        inputPanel4Layout.setHorizontalGroup(
            inputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel4Layout.setVerticalGroup(
            inputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel4)
                .addGap(18, 18, 18)
                .addComponent(horseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel5.setText("Suspension Type");

        suspTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel5Layout = new javax.swing.GroupLayout(inputPanel5);
        inputPanel5.setLayout(inputPanel5Layout);
        inputPanel5Layout.setHorizontalGroup(
            inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suspTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel5))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel5Layout.setVerticalGroup(
            inputPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel5)
                .addGap(18, 18, 18)
                .addComponent(suspTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel6.setText("Drive Type");

        driveTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel6Layout = new javax.swing.GroupLayout(inputPanel6);
        inputPanel6.setLayout(inputPanel6Layout);
        inputPanel6Layout.setHorizontalGroup(
            inputPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel6))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel6Layout.setVerticalGroup(
            inputPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel6)
                .addGap(18, 18, 18)
                .addComponent(driveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel7.setText("Gearbox Type");

        gearTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel7Layout = new javax.swing.GroupLayout(inputPanel7);
        inputPanel7.setLayout(inputPanel7Layout);
        inputPanel7Layout.setHorizontalGroup(
            inputPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gearTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel7Layout.setVerticalGroup(
            inputPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel7)
                .addGap(18, 18, 18)
                .addComponent(gearTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel8.setText("Speed Count");

        speedTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel8Layout = new javax.swing.GroupLayout(inputPanel8);
        inputPanel8.setLayout(inputPanel8Layout);
        inputPanel8Layout.setHorizontalGroup(
            inputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel8))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel8Layout.setVerticalGroup(
            inputPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel8)
                .addGap(18, 18, 18)
                .addComponent(speedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel9.setText("Fuel Type");

        fuelTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel9Layout = new javax.swing.GroupLayout(inputPanel9);
        inputPanel9.setLayout(inputPanel9Layout);
        inputPanel9Layout.setHorizontalGroup(
            inputPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fuelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel9))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel9Layout.setVerticalGroup(
            inputPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel9)
                .addGap(18, 18, 18)
                .addComponent(fuelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel10.setText("Interior");

        interTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel10Layout = new javax.swing.GroupLayout(inputPanel10);
        inputPanel10.setLayout(inputPanel10Layout);
        inputPanel10Layout.setHorizontalGroup(
            inputPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel10))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel10Layout.setVerticalGroup(
            inputPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel10)
                .addGap(18, 18, 18)
                .addComponent(interTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel11.setText("Body Kit");

        bodyTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel11Layout = new javax.swing.GroupLayout(inputPanel11);
        inputPanel11.setLayout(inputPanel11Layout);
        inputPanel11Layout.setHorizontalGroup(
            inputPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bodyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel11))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel11Layout.setVerticalGroup(
            inputPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel11)
                .addGap(18, 18, 18)
                .addComponent(bodyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel12.setText("Weight");

        weightTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel12Layout = new javax.swing.GroupLayout(inputPanel12);
        inputPanel12.setLayout(inputPanel12Layout);
        inputPanel12Layout.setHorizontalGroup(
            inputPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel12))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel12Layout.setVerticalGroup(
            inputPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel12)
                .addGap(18, 18, 18)
                .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel13.setText("Price");

        priceTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel13Layout = new javax.swing.GroupLayout(inputPanel13);
        inputPanel13.setLayout(inputPanel13Layout);
        inputPanel13Layout.setHorizontalGroup(
            inputPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel13))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel13Layout.setVerticalGroup(
            inputPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel13)
                .addGap(18, 18, 18)
                .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        infoLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        infoLabel14.setText("Name");

        nameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout inputPanel14Layout = new javax.swing.GroupLayout(inputPanel14);
        inputPanel14.setLayout(inputPanel14Layout);
        inputPanel14Layout.setHorizontalGroup(
            inputPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel14))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inputPanel14Layout.setVerticalGroup(
            inputPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel14)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout allInputsPanelsLayout = new javax.swing.GroupLayout(allInputsPanels);
        allInputsPanels.setLayout(allInputsPanelsLayout);
        allInputsPanelsLayout.setHorizontalGroup(
            allInputsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allInputsPanelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allInputsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        allInputsPanelsLayout.setVerticalGroup(
            allInputsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allInputsPanelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputScrollPane.setViewportView(allInputsPanels);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(saveButton)
                .addGap(90, 90, 90)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(4, 4, 4)
                .addComponent(inputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText();
        String engineName = engTextField.getText();
        String engType = engTypeComboBox.getSelectedItem().toString();
        String engVol = engVolTextField.getText();
        String horsepower = horseTextField.getText();
        String suspType = suspTypeComboBox.getSelectedItem().toString();
        String driveType = driveTypeComboBox.getSelectedItem().toString();
        String gearboxType = gearTypeComboBox.getSelectedItem().toString();
        String speedCount = speedTextField.getText();
        String fuelType = fuelTypeComboBox.getSelectedItem().toString();
        String interior = interTextField.getText();
        String bodyKit = bodyTextField.getText();
        String weight = weightTextField.getText();
        String price = priceTextField.getText();
        
        boolean isProcessed;
        String processedText;

        if (equipment == null) {
            isProcessed = equipmentController.saveEquipment(automobile, name, engineName, engType, engVol, horsepower, suspType, driveType, gearboxType, speedCount, fuelType, interior, bodyKit, weight, price);
            processedText = "Equipment for '" + automobile.getMark() + " " + automobile.getModel() + "' was added!";
        } else {
            isProcessed = equipmentController.updateEquipment(equipment, name, engineName, engType, engVol, horsepower, suspType, driveType, gearboxType, speedCount, fuelType, interior, bodyKit, weight, price);
            processedText = "Equipment for '" + automobile.getMark() + " " + automobile.getModel() + "' was updated!";
        }
        
        if (isProcessed) {
            JOptionPane.showMessageDialog(this, processedText, "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            this.lastForm.showWindow();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Some error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.lastForm.showWindow();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.lastForm.showWindow();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allInputsPanels;
    private javax.swing.JPanel autoPanel;
    private javax.swing.JTextField bodyTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> driveTypeComboBox;
    private javax.swing.JTextField engTextField;
    private javax.swing.JComboBox<String> engTypeComboBox;
    private javax.swing.JTextField engVolTextField;
    private javax.swing.JComboBox<String> fuelTypeComboBox;
    private javax.swing.JComboBox<String> gearTypeComboBox;
    private javax.swing.JTextField horseTextField;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel10;
    private javax.swing.JLabel infoLabel11;
    private javax.swing.JLabel infoLabel12;
    private javax.swing.JLabel infoLabel13;
    private javax.swing.JLabel infoLabel14;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JLabel infoLabel4;
    private javax.swing.JLabel infoLabel5;
    private javax.swing.JLabel infoLabel6;
    private javax.swing.JLabel infoLabel7;
    private javax.swing.JLabel infoLabel8;
    private javax.swing.JLabel infoLabel9;
    private javax.swing.JPanel inputPanel1;
    private javax.swing.JPanel inputPanel10;
    private javax.swing.JPanel inputPanel11;
    private javax.swing.JPanel inputPanel12;
    private javax.swing.JPanel inputPanel13;
    private javax.swing.JPanel inputPanel14;
    private javax.swing.JPanel inputPanel2;
    private javax.swing.JPanel inputPanel3;
    private javax.swing.JPanel inputPanel4;
    private javax.swing.JPanel inputPanel5;
    private javax.swing.JPanel inputPanel6;
    private javax.swing.JPanel inputPanel7;
    private javax.swing.JPanel inputPanel8;
    private javax.swing.JPanel inputPanel9;
    private javax.swing.JScrollPane inputScrollPane;
    private javax.swing.JTextField interTextField;
    private javax.swing.JLabel markLabel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField speedTextField;
    private javax.swing.JComboBox<String> suspTypeComboBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
