/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.college.view;

import com.college.view.interfaces.Showable;
import java.awt.Component;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vagid Zibliuc
 */
public class AutoWindow extends javax.swing.JFrame implements Showable{
    private final Showable lastWindow;
    
    /**
     * Creates new form AutoWindow
     */
    public AutoWindow() {
        initComponents();
        this.lastWindow = null;
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form AutoWindow
     * @param lastWindow
     */
    public AutoWindow(Showable lastWindow) {
        initComponents();
        this.lastWindow = lastWindow;
        this.setLocationRelativeTo(null);        
    }
    
    /**
     * Custom initialization of components
     */
    @Deprecated
    private void customInitComponents() {
        //priceSlider.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterPanel = new javax.swing.JPanel();
        bodyLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        sedanCheckBox = new javax.swing.JCheckBox();
        coupeCheckBox = new javax.swing.JCheckBox();
        suvCheckBox = new javax.swing.JCheckBox();
        pickupCheckBox = new javax.swing.JCheckBox();
        vanCheckBox = new javax.swing.JCheckBox();
        pricePanel = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        priceSlider = new javax.swing.JSlider();
        priceRangeLabel = new javax.swing.JLabel();
        enginePanel = new javax.swing.JPanel();
        engineLabel = new javax.swing.JLabel();
        electricCheckBox = new javax.swing.JCheckBox();
        gasolineCheckBox = new javax.swing.JCheckBox();
        diselCheckBox = new javax.swing.JCheckBox();
        gearboxPanel = new javax.swing.JPanel();
        gearboxLabel = new javax.swing.JLabel();
        autoCheckBox = new javax.swing.JCheckBox();
        mechanCheckBox = new javax.swing.JCheckBox();
        seqCheckBox = new javax.swing.JCheckBox();
        mainPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        descPrice = new javax.swing.JToggleButton();
        ascPrice = new javax.swing.JToggleButton();
        ratingButton = new javax.swing.JToggleButton();
        autoViewPanel = new javax.swing.JPanel();
        autoPanel2 = new javax.swing.JPanel();
        autoImg2 = new javax.swing.JLabel();
        autoText2 = new javax.swing.JLabel();
        autoPrice2 = new javax.swing.JLabel();
        autoPanel1 = new javax.swing.JPanel();
        autoImg1 = new javax.swing.JLabel();
        autoText1 = new javax.swing.JLabel();
        autoPrice1 = new javax.swing.JLabel();
        autoPanel3 = new javax.swing.JPanel();
        autoImg3 = new javax.swing.JLabel();
        autoText3 = new javax.swing.JLabel();
        autoPrice3 = new javax.swing.JLabel();
        autoPanel4 = new javax.swing.JPanel();
        autoImg4 = new javax.swing.JLabel();
        autoText4 = new javax.swing.JLabel();
        autoPrice4 = new javax.swing.JLabel();
        autoPanel5 = new javax.swing.JPanel();
        autoImg5 = new javax.swing.JLabel();
        autoText5 = new javax.swing.JLabel();
        autoPrice5 = new javax.swing.JLabel();
        autoPanel6 = new javax.swing.JPanel();
        autoImg6 = new javax.swing.JLabel();
        autoText6 = new javax.swing.JLabel();
        autoPrice6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        hometsItem = new javax.swing.JMenu();
        automobilesItem = new javax.swing.JMenu();
        dealrsItem = new javax.swing.JMenu();
        pricingItem = new javax.swing.JMenu();
        contactsItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Automobiles");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        filterPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        bodyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        bodyLabel.setText("Body Type");

        sedanCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        sedanCheckBox.setSelected(true);
        sedanCheckBox.setText("Sedan");
        sedanCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        coupeCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        coupeCheckBox.setSelected(true);
        coupeCheckBox.setText("Coupe");
        coupeCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        suvCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        suvCheckBox.setSelected(true);
        suvCheckBox.setText("SUV");
        suvCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        pickupCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        pickupCheckBox.setSelected(true);
        pickupCheckBox.setText("Pick-Up");
        pickupCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        vanCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        vanCheckBox.setSelected(true);
        vanCheckBox.setText("Mini-van");
        vanCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sedanCheckBox)
                    .addComponent(coupeCheckBox)
                    .addComponent(suvCheckBox)
                    .addComponent(pickupCheckBox)
                    .addComponent(vanCheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(sedanCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coupeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suvCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pickupCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vanCheckBox))
        );

        priceLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        priceLabel.setText("Price");

        priceSlider.setMaximum(100000);
        priceSlider.setMinimum(1000);
        priceSlider.setValue(2000);
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });

        priceRangeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        priceRangeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceRangeLabel.setText("1000$-2000$");

        javax.swing.GroupLayout pricePanelLayout = new javax.swing.GroupLayout(pricePanel);
        pricePanel.setLayout(pricePanelLayout);
        pricePanelLayout.setHorizontalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(priceRangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(priceSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pricePanelLayout.setVerticalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addGroup(pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceRangeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        engineLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        engineLabel.setText("Engine");

        electricCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        electricCheckBox.setSelected(true);
        electricCheckBox.setText("Electric");
        electricCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        gasolineCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        gasolineCheckBox.setSelected(true);
        gasolineCheckBox.setText("Gasoline");
        gasolineCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        diselCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        diselCheckBox.setSelected(true);
        diselCheckBox.setText("Disel");
        diselCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout enginePanelLayout = new javax.swing.GroupLayout(enginePanel);
        enginePanel.setLayout(enginePanelLayout);
        enginePanelLayout.setHorizontalGroup(
            enginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enginePanelLayout.createSequentialGroup()
                .addGroup(enginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(engineLabel)
                    .addComponent(electricCheckBox)
                    .addComponent(gasolineCheckBox)
                    .addComponent(diselCheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        enginePanelLayout.setVerticalGroup(
            enginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enginePanelLayout.createSequentialGroup()
                .addComponent(engineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electricCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gasolineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diselCheckBox)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        gearboxLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        gearboxLabel.setText("Gearbox");

        autoCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        autoCheckBox.setSelected(true);
        autoCheckBox.setText("Automat");
        autoCheckBox.setActionCommand("Automatic");
        autoCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        mechanCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        mechanCheckBox.setSelected(true);
        mechanCheckBox.setText("Mechanic");
        mechanCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        seqCheckBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        seqCheckBox.setSelected(true);
        seqCheckBox.setText("Sequental");
        seqCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gearboxPanelLayout = new javax.swing.GroupLayout(gearboxPanel);
        gearboxPanel.setLayout(gearboxPanelLayout);
        gearboxPanelLayout.setHorizontalGroup(
            gearboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gearboxPanelLayout.createSequentialGroup()
                .addGroup(gearboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gearboxLabel)
                    .addComponent(autoCheckBox)
                    .addComponent(mechanCheckBox)
                    .addComponent(seqCheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gearboxPanelLayout.setVerticalGroup(
            gearboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gearboxPanelLayout.createSequentialGroup()
                .addComponent(gearboxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mechanCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seqCheckBox))
        );

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bodyLabel)
                    .addComponent(pricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enginePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gearboxPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bodyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enginePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gearboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        searchField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchField.setText("Search");
        searchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        descPrice.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        descPrice.setText("Price descending");

        ascPrice.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ascPrice.setText("Price ascending");

        ratingButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ratingButton.setText("Rating");

        autoPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        autoPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPanel1MouseClicked(evt);
            }
        });

        autoImg2.setBackground(new java.awt.Color(153, 153, 153));
        autoImg2.setText("img");
        autoImg2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        autoText2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autoText2.setText("Text");

        autoPrice2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        autoPrice2.setText("0 $");

        javax.swing.GroupLayout autoPanel2Layout = new javax.swing.GroupLayout(autoPanel2);
        autoPanel2.setLayout(autoPanel2Layout);
        autoPanel2Layout.setHorizontalGroup(
            autoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(autoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoPrice2)
                    .addComponent(autoText2)
                    .addComponent(autoImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        autoPanel2Layout.setVerticalGroup(
            autoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(autoImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPrice2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        autoPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        autoPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPanel1MouseClicked(evt);
            }
        });

        autoImg1.setBackground(new java.awt.Color(153, 153, 153));
        autoImg1.setText("img");
        autoImg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        autoText1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autoText1.setText("Text");

        autoPrice1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        autoPrice1.setText("0 $");

        javax.swing.GroupLayout autoPanel1Layout = new javax.swing.GroupLayout(autoPanel1);
        autoPanel1.setLayout(autoPanel1Layout);
        autoPanel1Layout.setHorizontalGroup(
            autoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(autoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoPrice1)
                    .addComponent(autoText1)
                    .addComponent(autoImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        autoPanel1Layout.setVerticalGroup(
            autoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(autoImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPrice1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autoPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        autoPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPanel1MouseClicked(evt);
            }
        });

        autoImg3.setBackground(new java.awt.Color(153, 153, 153));
        autoImg3.setText("img");
        autoImg3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        autoText3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autoText3.setText("Text");

        autoPrice3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        autoPrice3.setText("0 $");

        javax.swing.GroupLayout autoPanel3Layout = new javax.swing.GroupLayout(autoPanel3);
        autoPanel3.setLayout(autoPanel3Layout);
        autoPanel3Layout.setHorizontalGroup(
            autoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(autoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoPrice3)
                    .addComponent(autoText3)
                    .addComponent(autoImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        autoPanel3Layout.setVerticalGroup(
            autoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(autoImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPrice3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autoPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        autoPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPanel1MouseClicked(evt);
            }
        });

        autoImg4.setBackground(new java.awt.Color(153, 153, 153));
        autoImg4.setText("img");
        autoImg4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        autoText4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autoText4.setText("Text");

        autoPrice4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        autoPrice4.setText("0 $");

        javax.swing.GroupLayout autoPanel4Layout = new javax.swing.GroupLayout(autoPanel4);
        autoPanel4.setLayout(autoPanel4Layout);
        autoPanel4Layout.setHorizontalGroup(
            autoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(autoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoPrice4)
                    .addComponent(autoText4)
                    .addComponent(autoImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        autoPanel4Layout.setVerticalGroup(
            autoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(autoImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoText4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPrice4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        autoPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        autoPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPanel1MouseClicked(evt);
            }
        });

        autoImg5.setBackground(new java.awt.Color(153, 153, 153));
        autoImg5.setText("img");
        autoImg5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        autoText5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autoText5.setText("Text");

        autoPrice5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        autoPrice5.setText("0 $");

        javax.swing.GroupLayout autoPanel5Layout = new javax.swing.GroupLayout(autoPanel5);
        autoPanel5.setLayout(autoPanel5Layout);
        autoPanel5Layout.setHorizontalGroup(
            autoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(autoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoPrice5)
                    .addComponent(autoText5)
                    .addComponent(autoImg5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        autoPanel5Layout.setVerticalGroup(
            autoPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(autoImg5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoText5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPrice5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autoPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        autoPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPanel1MouseClicked(evt);
            }
        });

        autoImg6.setBackground(new java.awt.Color(153, 153, 153));
        autoImg6.setText("img");
        autoImg6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        autoText6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autoText6.setText("Text");

        autoPrice6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        autoPrice6.setText("0 $");

        javax.swing.GroupLayout autoPanel6Layout = new javax.swing.GroupLayout(autoPanel6);
        autoPanel6.setLayout(autoPanel6Layout);
        autoPanel6Layout.setHorizontalGroup(
            autoPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(autoPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoPrice6)
                    .addComponent(autoText6)
                    .addComponent(autoImg6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        autoPanel6Layout.setVerticalGroup(
            autoPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(autoImg6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoText6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPrice6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout autoViewPanelLayout = new javax.swing.GroupLayout(autoViewPanel);
        autoViewPanel.setLayout(autoViewPanelLayout);
        autoViewPanelLayout.setHorizontalGroup(
            autoViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autoViewPanelLayout.createSequentialGroup()
                .addGroup(autoViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(autoViewPanelLayout.createSequentialGroup()
                        .addComponent(autoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(autoPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(autoViewPanelLayout.createSequentialGroup()
                        .addComponent(autoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(autoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(autoViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(autoPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        autoViewPanelLayout.setVerticalGroup(
            autoViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoViewPanelLayout.createSequentialGroup()
                .addGroup(autoViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autoPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(autoViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(autoPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(ascPrice)
                .addGap(18, 18, 18)
                .addComponent(descPrice)
                .addGap(18, 18, 18)
                .addComponent(ratingButton)
                .addGap(19, 19, 19))
            .addComponent(autoViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratingButton)
                    .addComponent(ascPrice)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(autoViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuBar.setBorder(new javax.swing.border.MatteBorder(null));
        menuBar.setBorderPainted(false);
        menuBar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(314, 46));

        hometsItem.setText("Home");
        hometsItem.setAutoscrolls(true);
        hometsItem.setBorderPainted(false);
        hometsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hometsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hometsItemMouseClicked(evt);
            }
        });
        menuBar.add(hometsItem);

        automobilesItem.setText("Automobiles");
        automobilesItem.setEnabled(false);
        automobilesItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        automobilesItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                automobilesItemMouseClicked(evt);
            }
        });
        menuBar.add(automobilesItem);

        dealrsItem.setText("Dealers");
        dealrsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        dealrsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dealrsItemMouseClicked(evt);
            }
        });
        menuBar.add(dealrsItem);

        pricingItem.setText("Pricing");
        pricingItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        pricingItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pricingItemMouseClicked(evt);
            }
        });
        menuBar.add(pricingItem);

        contactsItem.setText("Contacts");
        contactsItem.setAutoscrolls(true);
        contactsItem.setBorderPainted(false);
        contactsItem.setEnabled(false);
        contactsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        menuBar.add(contactsItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (lastWindow != null)
            lastWindow.showWindow();
        else 
            System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void automobilesItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_automobilesItemMouseClicked
        // TODO add your handling code here:
        new AutoWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_automobilesItemMouseClicked

    private void dealrsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealrsItemMouseClicked
        // TODO add your handling code here:
        new DealersWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_dealrsItemMouseClicked

    private void pricingItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricingItemMouseClicked
        // TODO add your handling code here:
        new BuyingWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_pricingItemMouseClicked

    private void hometsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometsItemMouseClicked
        // TODO add your handling code here:
        new HomeWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_hometsItemMouseClicked

    private void autoPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPanel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked on item!");
    }//GEN-LAST:event_autoPanel1MouseClicked

    /**
     * Changes range of prices
     * TODO: change it to two input fields
     * @param evt 
     */
    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSliderStateChanged
        // TODO add your handling code here:
        int value = priceSlider.getValue();
        priceRangeLabel.setText("1000$-" + value + '$');
    }//GEN-LAST:event_priceSliderStateChanged

    private void checkBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxMouseClicked
        // TODO add your handling code here:
        checkState();
    }//GEN-LAST:event_checkBoxMouseClicked
    
    private void checkState() {
        HashMap<String, Boolean> checkedItems = new HashMap<>();
        Component[] components = filterPanel.getComponents();
        for (Component component : components) {
            if (component instanceof JPanel) {
                Component[] panelComponents = ((JPanel) component).getComponents();
                for (Component panelComponent : panelComponents) {
                    if (panelComponent instanceof JCheckBox) {
                        JCheckBox checkBox = (JCheckBox) panelComponent;
                        checkedItems.put(checkBox.getActionCommand(), checkBox.isSelected());
                    }
                }
            }
        }
        
        StringBuilder builder = new StringBuilder("");
        for (Map.Entry<String, Boolean> checkbox : checkedItems.entrySet()) {
            builder.append(checkbox.getKey()).append(": ").append(checkbox.getValue()).append("\n");
        }
        JOptionPane.showMessageDialog(this, builder.toString());
    }
    
    @Override
    public void showWindow() {
        /* Display the form */
        this.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ascPrice;
    private javax.swing.JCheckBox autoCheckBox;
    private javax.swing.JLabel autoImg1;
    private javax.swing.JLabel autoImg2;
    private javax.swing.JLabel autoImg3;
    private javax.swing.JLabel autoImg4;
    private javax.swing.JLabel autoImg5;
    private javax.swing.JLabel autoImg6;
    private javax.swing.JPanel autoPanel1;
    private javax.swing.JPanel autoPanel2;
    private javax.swing.JPanel autoPanel3;
    private javax.swing.JPanel autoPanel4;
    private javax.swing.JPanel autoPanel5;
    private javax.swing.JPanel autoPanel6;
    private javax.swing.JLabel autoPrice1;
    private javax.swing.JLabel autoPrice2;
    private javax.swing.JLabel autoPrice3;
    private javax.swing.JLabel autoPrice4;
    private javax.swing.JLabel autoPrice5;
    private javax.swing.JLabel autoPrice6;
    private javax.swing.JLabel autoText1;
    private javax.swing.JLabel autoText2;
    private javax.swing.JLabel autoText3;
    private javax.swing.JLabel autoText4;
    private javax.swing.JLabel autoText5;
    private javax.swing.JLabel autoText6;
    private javax.swing.JPanel autoViewPanel;
    private javax.swing.JMenu automobilesItem;
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JMenu contactsItem;
    private javax.swing.JCheckBox coupeCheckBox;
    private javax.swing.JMenu dealrsItem;
    private javax.swing.JToggleButton descPrice;
    private javax.swing.JCheckBox diselCheckBox;
    private javax.swing.JCheckBox electricCheckBox;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JPanel enginePanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JCheckBox gasolineCheckBox;
    private javax.swing.JLabel gearboxLabel;
    private javax.swing.JPanel gearboxPanel;
    private javax.swing.JMenu hometsItem;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox mechanCheckBox;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JCheckBox pickupCheckBox;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JPanel pricePanel;
    private javax.swing.JLabel priceRangeLabel;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JMenu pricingItem;
    private javax.swing.JToggleButton ratingButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JCheckBox sedanCheckBox;
    private javax.swing.JCheckBox seqCheckBox;
    private javax.swing.JCheckBox suvCheckBox;
    private javax.swing.JCheckBox vanCheckBox;
    // End of variables declaration//GEN-END:variables

}
