/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.college.view;

import com.college.model.*;
import com.college.view.interfaces.Showable;
import com.college.view.utilites.ImageUploader;
import javax.swing.Icon;

/**
 *
 * @author Vagid Zibliuc
 */
public class ConfirmationWindow extends javax.swing.JFrame implements Showable {
    private Showable lastWindow;
    private Contract contract;

    /**
     * Creates new form ConfirmationWindow
     */
    public ConfirmationWindow() {
        initComponents();
        this.lastWindow = null;
        this.setLocationRelativeTo(null);
    }
    
    public ConfirmationWindow(Showable lastWindow, Contract contract) {
        initComponents();
        this.lastWindow = lastWindow;
        this.contract = contract;
        this.setLocationRelativeTo(null);
        customInitComponents();
    }
    
    private void customInitComponents() {
        Automobile auto = contract.getAutomobile();
        
        welcomeLabel.setText(auto.getMark());
        welcomeSubLable.setText(auto.getModel());
        
        Icon icon = ImageUploader.uploadImage(imageLabel.getWidth(), imageLabel.getHeight(), auto.getImagePath(), ImageUploader.WIDTH);
        imageLabel.setIcon(icon);
        
        Dealer dealer = contract.getDealer();
        
        nameLabel.setText(dealer.getName());
        addressLabel.setText(dealer.getAddress());
        discLabel.setText(dealer.getTelephone());
        
        User user = contract.getUser();
        
        userNameLabel.setText(user.getName());
        userSurnameLabel.setText(user.getSurname());
        userNumberLabel.setText(user.getTelephone());
        
        Equipment equipment = contract.getEquipment();
        
        compName.setText(equipment.getName());
        compPrice.setText(String.valueOf(equipment.getPrice()));
        
        //list
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = equipment.getShortEquipment();
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        elemOfList = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        discLabel = new javax.swing.JLabel();
        dealerLabel = new javax.swing.JLabel();
        elemPanel = new javax.swing.JPanel();
        compName = new javax.swing.JLabel();
        compPrice = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        mainPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        welcomeSubLable = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        elemOfList1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        userSurnameLabel = new javax.swing.JLabel();
        userNumberLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        hometsItem = new javax.swing.JMenu();
        automobilesItem = new javax.swing.JMenu();
        dealrsItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        elemOfList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList.setMaximumSize(new java.awt.Dimension(240, 153));
        elemOfList.setPreferredSize(new java.awt.Dimension(240, 153));

        nameLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nameLabel.setText("Name");

        addressLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        addressLabel.setText("Address");

        discLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        discLabel.setForeground(new java.awt.Color(153, 153, 153));
        discLabel.setText("Description");

        dealerLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dealerLabel.setText("Dealer");

        javax.swing.GroupLayout elemOfListLayout = new javax.swing.GroupLayout(elemOfList);
        elemOfList.setLayout(elemOfListLayout);
        elemOfListLayout.setHorizontalGroup(
            elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elemOfListLayout.createSequentialGroup()
                .addGroup(elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, elemOfListLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(dealerLabel)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, elemOfListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        elemOfListLayout.setVerticalGroup(
            elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discLabel)
                .addGap(18, 18, 18)
                .addComponent(dealerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        elemPanel.setBackground(new java.awt.Color(255, 255, 255));
        elemPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        compName.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        compName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compName.setText("Title");

        compPrice.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        compPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compPrice.setText("1500$");

        listScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        list.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listScrollPane.setViewportView(list);

        javax.swing.GroupLayout elemPanelLayout = new javax.swing.GroupLayout(elemPanel);
        elemPanel.setLayout(elemPanelLayout);
        elemPanelLayout.setHorizontalGroup(
            elemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(elemPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        elemPanelLayout.setVerticalGroup(
            elemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(compName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compPrice)
                .addGap(18, 18, 18)
                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        mainPanel1.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Automobile");
        welcomeLabel.setToolTipText("");
        mainPanel1.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 86, 490, -1));

        welcomeSubLable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        welcomeSubLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeSubLable.setText("Mark");
        mainPanel1.add(welcomeSubLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 152, 490, -1));

        imageLabel.setMaximumSize(new java.awt.Dimension(231, 500));
        mainPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 231));

        elemOfList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList1.setMaximumSize(new java.awt.Dimension(240, 153));
        elemOfList1.setPreferredSize(new java.awt.Dimension(240, 153));

        userNameLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        userNameLabel.setText("Name");

        userSurnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        userSurnameLabel.setText("Address");

        userNumberLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        userNumberLabel.setForeground(new java.awt.Color(153, 153, 153));
        userNumberLabel.setText("Description");

        userLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        userLabel.setText("User");

        javax.swing.GroupLayout elemOfList1Layout = new javax.swing.GroupLayout(elemOfList1);
        elemOfList1.setLayout(elemOfList1Layout);
        elemOfList1Layout.setHorizontalGroup(
            elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elemOfList1Layout.createSequentialGroup()
                .addGroup(elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, elemOfList1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(userLabel)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, elemOfList1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userSurnameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        elemOfList1Layout.setVerticalGroup(
            elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userSurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(userLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        confirmButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        confirmButton.setText("Confirm");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(elemOfList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(elemOfList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(elemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(confirmButton)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(elemOfList1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(elemOfList, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(elemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        menuBar.setBorder(new javax.swing.border.MatteBorder(null));
        menuBar.setBorderPainted(false);
        menuBar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(314, 46));

        hometsItem.setText("Home");
        hometsItem.setAutoscrolls(true);
        hometsItem.setBorderPainted(false);
        hometsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hometsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hometsItemMouseClicked(evt);
            }
        });
        menuBar.add(hometsItem);

        automobilesItem.setText("Automobiles");
        automobilesItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        automobilesItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                automobilesItemMouseClicked(evt);
            }
        });
        menuBar.add(automobilesItem);

        dealrsItem.setText("Dealers");
        dealrsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        dealrsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dealrsItemMouseClicked(evt);
            }
        });
        menuBar.add(dealrsItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hometsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometsItemMouseClicked
        // TODO add your handling code here:
        new HomeWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_hometsItemMouseClicked

    private void automobilesItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_automobilesItemMouseClicked
        // TODO add your handling code here:
        new AutoWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_automobilesItemMouseClicked

    private void dealrsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealrsItemMouseClicked
        // TODO add your handling code here:
        new DealersWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_dealrsItemMouseClicked

    @Override
    public void showWindow() {
        this.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JMenu automobilesItem;
    private javax.swing.JLabel compName;
    private javax.swing.JLabel compPrice;
    private javax.swing.JToggleButton confirmButton;
    private javax.swing.JLabel dealerLabel;
    private javax.swing.JMenu dealrsItem;
    private javax.swing.JLabel discLabel;
    private javax.swing.JPanel elemOfList;
    private javax.swing.JPanel elemOfList1;
    private javax.swing.JPanel elemPanel;
    private javax.swing.JMenu hometsItem;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JList<String> list;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNumberLabel;
    private javax.swing.JLabel userSurnameLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeSubLable;
    // End of variables declaration//GEN-END:variables

}
