/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.college.view;

import com.college.view.interfaces.Showable;

/**
 *
 * @author Vagid Zibliuc
 */
public class ConfirmationWindow extends javax.swing.JFrame implements Showable {
    private Showable lastWindow;

    /**
     * Creates new form ConfirmationWindow
     */
    public ConfirmationWindow() {
        initComponents();
        this.lastWindow = null;
        this.setLocationRelativeTo(null);
    }
    
    public ConfirmationWindow(Showable lastWindow) {
        initComponents();
        this.lastWindow = lastWindow;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        elemOfList = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        discLabel = new javax.swing.JLabel();
        dealerLabel = new javax.swing.JLabel();
        elemPanel = new javax.swing.JPanel();
        compName = new javax.swing.JLabel();
        compName1 = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        mainPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        welcomeSubLable = new javax.swing.JLabel();
        elemOfList1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        discLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        hometsItem = new javax.swing.JMenu();
        automobilesItem = new javax.swing.JMenu();
        dealrsItem = new javax.swing.JMenu();
        pricingItem = new javax.swing.JMenu();
        contactsItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        elemOfList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemOfListMouseClicked(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nameLabel.setText("Name");

        addressLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        addressLabel.setText("Address");

        discLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        discLabel.setForeground(new java.awt.Color(153, 153, 153));
        discLabel.setText("Description");

        dealerLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dealerLabel.setText("Dealer");

        javax.swing.GroupLayout elemOfListLayout = new javax.swing.GroupLayout(elemOfList);
        elemOfList.setLayout(elemOfListLayout);
        elemOfListLayout.setHorizontalGroup(
            elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfListLayout.createSequentialGroup()
                .addGroup(elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elemOfListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(addressLabel)
                            .addComponent(discLabel)))
                    .addGroup(elemOfListLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(dealerLabel)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        elemOfListLayout.setVerticalGroup(
            elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discLabel)
                .addGap(18, 18, 18)
                .addComponent(dealerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        elemPanel.setBackground(new java.awt.Color(255, 255, 255));
        elemPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        compName.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        compName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compName.setText("Title");

        compName1.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        compName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compName1.setText("1500$");

        listScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        list.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listScrollPane.setViewportView(list);

        javax.swing.GroupLayout elemPanelLayout = new javax.swing.GroupLayout(elemPanel);
        elemPanel.setLayout(elemPanelLayout);
        elemPanelLayout.setHorizontalGroup(
            elemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(elemPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        elemPanelLayout.setVerticalGroup(
            elemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(compName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compName1)
                .addGap(18, 18, 18)
                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel1.setBackground(new java.awt.Color(204, 204, 204));

        welcomeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Automobile");
        welcomeLabel.setToolTipText("");

        welcomeSubLable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        welcomeSubLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeSubLable.setText("Mark");

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeSubLable)
                        .addGap(229, 229, 229))))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(welcomeSubLable)
                .addGap(54, 54, 54))
        );

        elemOfList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemOfList1MouseClicked(evt);
            }
        });

        nameLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nameLabel1.setText("Name");

        addressLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        addressLabel1.setText("Address");

        discLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        discLabel1.setForeground(new java.awt.Color(153, 153, 153));
        discLabel1.setText("Description");

        userLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        userLabel.setText("User");

        javax.swing.GroupLayout elemOfList1Layout = new javax.swing.GroupLayout(elemOfList1);
        elemOfList1.setLayout(elemOfList1Layout);
        elemOfList1Layout.setHorizontalGroup(
            elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList1Layout.createSequentialGroup()
                .addGroup(elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elemOfList1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel1)
                            .addComponent(addressLabel1)
                            .addComponent(discLabel1)))
                    .addGroup(elemOfList1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(userLabel)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        elemOfList1Layout.setVerticalGroup(
            elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discLabel1)
                .addGap(18, 18, 18)
                .addComponent(userLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        confirmButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        confirmButton.setText("Confirm");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(elemOfList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(elemOfList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(elemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(232, 232, 232))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(elemOfList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(elemOfList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(elemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        menuBar.setBorder(new javax.swing.border.MatteBorder(null));
        menuBar.setBorderPainted(false);
        menuBar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(314, 46));

        hometsItem.setText("Home");
        hometsItem.setAutoscrolls(true);
        hometsItem.setBorderPainted(false);
        hometsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hometsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hometsItemMouseClicked(evt);
            }
        });
        menuBar.add(hometsItem);

        automobilesItem.setText("Automobiles");
        automobilesItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        automobilesItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                automobilesItemMouseClicked(evt);
            }
        });
        menuBar.add(automobilesItem);

        dealrsItem.setText("Dealers");
        dealrsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        dealrsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dealrsItemMouseClicked(evt);
            }
        });
        menuBar.add(dealrsItem);

        pricingItem.setText("Pricing");
        pricingItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        pricingItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pricingItemMouseClicked(evt);
            }
        });
        menuBar.add(pricingItem);

        contactsItem.setText("Contacts");
        contactsItem.setAutoscrolls(true);
        contactsItem.setBorderPainted(false);
        contactsItem.setEnabled(false);
        contactsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        menuBar.add(contactsItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hometsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometsItemMouseClicked
        // TODO add your handling code here:
        new HomeWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_hometsItemMouseClicked

    private void automobilesItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_automobilesItemMouseClicked
        // TODO add your handling code here:
        new AutoWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_automobilesItemMouseClicked

    private void dealrsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealrsItemMouseClicked
        // TODO add your handling code here:
        new DealersWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_dealrsItemMouseClicked

    private void pricingItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricingItemMouseClicked
        // TODO add your handling code here:
        new BuyingWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_pricingItemMouseClicked

    private void elemOfListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemOfListMouseClicked
        // TODO add your handling code here:
//        if (evt.getComponent() instanceof JPanel) {
//            JPanel clickedPanel = (JPanel) evt.getComponent();
//            if (clickedPanel.getComponent(0) instanceof JLabel) {
//                String message = "Clicked panel name of label = " + ((JLabel)clickedPanel.getComponent(0)).getText();
//                JOptionPane.showMessageDialog(this, "You clicked the dealers button!\n" + message);
//            }
//        }
    }//GEN-LAST:event_elemOfListMouseClicked

    private void elemOfList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemOfList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elemOfList1MouseClicked

    @Override
    public void showWindow() {
        this.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConfirmationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConfirmationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConfirmationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConfirmationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConfirmationWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JMenu automobilesItem;
    private javax.swing.JLabel compName;
    private javax.swing.JLabel compName1;
    private javax.swing.JToggleButton confirmButton;
    private javax.swing.JMenu contactsItem;
    private javax.swing.JLabel dealerLabel;
    private javax.swing.JMenu dealrsItem;
    private javax.swing.JLabel discLabel;
    private javax.swing.JLabel discLabel1;
    private javax.swing.JPanel elemOfList;
    private javax.swing.JPanel elemOfList1;
    private javax.swing.JPanel elemPanel;
    private javax.swing.JMenu hometsItem;
    private javax.swing.JList<String> list;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JMenu pricingItem;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeSubLable;
    // End of variables declaration//GEN-END:variables

}
