/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.college.view;

import com.college.view.interfaces.Showable;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JLabel;

/**
 *
 * @author Vagid Zibliuc
 */
public class DealersWindow extends javax.swing.JFrame implements Showable {

    private final Showable lastWindow;

    /**
     * Creates new form DealersWindow
     */
    public DealersWindow() {
        initComponents();
        this.lastWindow = null;
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form DealersWindow
     *
     * @param lastWindow
     */
    public DealersWindow(Showable lastWindow) {
        initComponents();
        this.lastWindow = lastWindow;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        welcomeSubLable = new javax.swing.JLabel();
        dealersPanel = new javax.swing.JPanel();
        dealersLabel = new javax.swing.JLabel();
        dealersSubLabel = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        elemOfList = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        discLabel = new javax.swing.JLabel();
        elemOfList1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        discLabel1 = new javax.swing.JLabel();
        elemOfList2 = new javax.swing.JPanel();
        nameLabel2 = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        discLabel2 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        hometsItem = new javax.swing.JMenu();
        automobilesItem = new javax.swing.JMenu();
        dealrsItem = new javax.swing.JMenu();
        pricingItem = new javax.swing.JMenu();
        contactsItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        welcomeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Dealers");
        welcomeLabel.setToolTipText("");

        welcomeSubLable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        welcomeSubLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeSubLable.setText("All for you");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(welcomeSubLable)
                        .addGap(364, 364, 364))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(welcomeSubLable)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        dealersLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        dealersLabel.setText("List of dealers");

        dealersSubLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dealersSubLabel.setText("Choose the dealer");

        elemOfList.setBackground(new java.awt.Color(255, 255, 255));
        elemOfList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemOfListMouseClicked(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nameLabel.setText("Name");

        addressLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        addressLabel.setText("Address");

        discLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        discLabel.setForeground(new java.awt.Color(153, 153, 153));
        discLabel.setText("Description");

        javax.swing.GroupLayout elemOfListLayout = new javax.swing.GroupLayout(elemOfList);
        elemOfList.setLayout(elemOfListLayout);
        elemOfListLayout.setHorizontalGroup(
            elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(addressLabel)
                    .addComponent(discLabel))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        elemOfListLayout.setVerticalGroup(
            elemOfListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        elemOfList1.setBackground(new java.awt.Color(255, 255, 255));
        elemOfList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemOfListMouseClicked(evt);
            }
        });

        nameLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nameLabel1.setText("Name");

        addressLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        addressLabel1.setText("Address");

        discLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        discLabel1.setForeground(new java.awt.Color(153, 153, 153));
        discLabel1.setText("Description");

        javax.swing.GroupLayout elemOfList1Layout = new javax.swing.GroupLayout(elemOfList1);
        elemOfList1.setLayout(elemOfList1Layout);
        elemOfList1Layout.setHorizontalGroup(
            elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel1)
                    .addComponent(addressLabel1)
                    .addComponent(discLabel1))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        elemOfList1Layout.setVerticalGroup(
            elemOfList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        elemOfList2.setBackground(new java.awt.Color(255, 255, 255));
        elemOfList2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        elemOfList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemOfListMouseClicked(evt);
            }
        });

        nameLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nameLabel2.setText("Name");

        addressLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        addressLabel2.setText("Address");

        discLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        discLabel2.setForeground(new java.awt.Color(153, 153, 153));
        discLabel2.setText("Description");

        javax.swing.GroupLayout elemOfList2Layout = new javax.swing.GroupLayout(elemOfList2);
        elemOfList2.setLayout(elemOfList2Layout);
        elemOfList2Layout.setHorizontalGroup(
            elemOfList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(elemOfList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel2)
                    .addComponent(addressLabel2)
                    .addComponent(discLabel2))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        elemOfList2Layout.setVerticalGroup(
            elemOfList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elemOfList2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(elemOfList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(elemOfList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(elemOfList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elemOfList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elemOfList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elemOfList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        confirmButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        confirmButton.setText("Next");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dealersPanelLayout = new javax.swing.GroupLayout(dealersPanel);
        dealersPanel.setLayout(dealersPanelLayout);
        dealersPanelLayout.setHorizontalGroup(
            dealersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dealersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dealersPanelLayout.createSequentialGroup()
                        .addGroup(dealersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealersSubLabel)
                            .addComponent(dealersLabel)
                            .addGroup(dealersPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dealersPanelLayout.createSequentialGroup()
                        .addComponent(confirmButton)
                        .addGap(353, 353, 353))))
        );
        dealersPanelLayout.setVerticalGroup(
            dealersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealersPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dealersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealersSubLabel)
                .addGap(18, 18, 18)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        menuBar.setBorder(new javax.swing.border.MatteBorder(null));
        menuBar.setBorderPainted(false);
        menuBar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(314, 46));

        hometsItem.setText("Home");
        hometsItem.setAutoscrolls(true);
        hometsItem.setBorderPainted(false);
        hometsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hometsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hometsItemMouseClicked(evt);
            }
        });
        menuBar.add(hometsItem);

        automobilesItem.setText("Automobiles");
        automobilesItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        automobilesItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                automobilesItemMouseClicked(evt);
            }
        });
        menuBar.add(automobilesItem);

        dealrsItem.setText("Dealers");
        dealrsItem.setEnabled(false);
        dealrsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        dealrsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dealrsItemMouseClicked(evt);
            }
        });
        menuBar.add(dealrsItem);

        pricingItem.setText("Pricing");
        pricingItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        pricingItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pricingItemMouseClicked(evt);
            }
        });
        menuBar.add(pricingItem);

        contactsItem.setText("Contacts");
        contactsItem.setAutoscrolls(true);
        contactsItem.setBorderPainted(false);
        contactsItem.setEnabled(false);
        contactsItem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        menuBar.add(contactsItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dealersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (lastWindow != null)
            lastWindow.showWindow();
        else
            System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void hometsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometsItemMouseClicked
        // TODO add your handling code here:
        new HomeWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_hometsItemMouseClicked

    private void automobilesItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_automobilesItemMouseClicked
        // TODO add your handling code here:
        new AutoWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_automobilesItemMouseClicked

    private void dealrsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dealrsItemMouseClicked
        // TODO add your handling code here:
        new DealersWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_dealrsItemMouseClicked

    private void pricingItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricingItemMouseClicked
        // TODO add your handling code here:
        new BuyingWindow().showWindow();
        this.dispose();
    }//GEN-LAST:event_pricingItemMouseClicked

    private void setBlack(JPanel clickedPanel) {
        clickedPanel.setBackground(Color.black);
        for (Component cmp : clickedPanel.getComponents()) {
            if (cmp instanceof JLabel) {
                cmp.setForeground(Color.white);
            }
        }
    }

    private void setAllWhite(JPanel parent) {
        for (Component panel : parent.getComponents()) {
            if (panel instanceof JPanel) {
                panel.setBackground(Color.white);
                for (Component cmp : ((JPanel) panel).getComponents()) {
                    if (cmp instanceof JLabel) {
                        cmp.setForeground(Color.black);
                    }
                }
            }
        }
    }


    private void elemOfListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemOfListMouseClicked
        // TODO add your handling code here:
        JPanel panel = (JPanel) evt.getComponent();
        setAllWhite((JPanel) panel.getParent());
        setBlack(panel);
    }//GEN-LAST:event_elemOfListMouseClicked

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        new ConfirmationWindow(this).showWindow();
        this.dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    @Override
    public void showWindow() {
        /* Create and display the form */
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JMenu automobilesItem;
    private javax.swing.JToggleButton confirmButton;
    private javax.swing.JMenu contactsItem;
    private javax.swing.JLabel dealersLabel;
    private javax.swing.JPanel dealersPanel;
    private javax.swing.JLabel dealersSubLabel;
    private javax.swing.JMenu dealrsItem;
    private javax.swing.JLabel discLabel;
    private javax.swing.JLabel discLabel1;
    private javax.swing.JLabel discLabel2;
    private javax.swing.JPanel elemOfList;
    private javax.swing.JPanel elemOfList1;
    private javax.swing.JPanel elemOfList2;
    private javax.swing.JMenu hometsItem;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JMenu pricingItem;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeSubLable;
    // End of variables declaration//GEN-END:variables

}
